// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tivziiekpgqxaizqqfjg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpdnppaWVrcGdxeGFpenFxZmpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTU3MzcsImV4cCI6MjA2NTQ3MTczN30.Q1KUa1k0kXps6jSKQvxiaPka6wZvItpA10Q04af-cCA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);